### ISSUE TITLE
Beresad ult displays incorrectly

### ISSUE THREAD

**Issue by AerisDraco** [ironhidegames/issues-kr4#90]
I believe this was also an issue with Eiskalt's ult, where the screen effect does not cover the entire screen, missing the leftmost fifth or so.

**Comment by cigumo** [comment]
fixed in 1.9.9.7

**Comment by Mmlh1** [comment]
https://github.com/ironhidegames/issues-kr4/assets/40719238/d1ff37ed-12cc-4817-9343-cfe6b93cc0a0

![image](https://github.com/ironhidegames/issues-kr4/assets/40719238/b60b4753-25aa-4a98-8a30-43c29e4b0f30)

The background effect still does not cover the full screen.
A similar thing applies to mobile, but there only a strip on the left is affected, and it does extend all the way to the right.

**Comment by Mmlh1** [comment]
https://github.com/ironhidegames/issues-kr4/assets/40719238/22c13bb3-69bb-4a91-8d21-907220933eac

The bug on mobile, where the left side is missing

**Comment by pablorealini** [comment]
What is the bug in mobile?

**Comment by Mmlh1** [comment]
Same as on pc with those background particles, but only missing on the left side of the screen.

**Comment by Mmlh1** [comment]
Also I doubt this deserves prio high but since it says that is set by developers, I didn't remove it when reopening it.

**Comment by pablorealini** [comment]
Agree this is no prio high.

**Comment by cigumo** [comment]
fixed in v.1.16.3
